fn main() {
    cbindgen::Builder::new()
        .with_crate_name("fabric_capability_ffi")
        .with_include_comment("// Fabric capability FFI — auto-generated by cbindgen")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("fabric_capability.h");
}
